In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv(r"E:\engg\Data\E_Com\e_commerce_messy.csv")

In [3]:
df.head()

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,100,Customer_100,ORD-41285,11/22/2024,Blender,Home,3,38,Cash on Delivery,Shipped,114.00
1,101,Customer_101,ORD-35783,07-05-2025,Smartphone,Electronics,2,abd,PayPal,Processing,NaN
2,102,Customer_102,ORD-84355,12/23/2024,Tennis Racket,Sports,1,389.05,PayPal,Delivered,389.05
3,103,Customer_103,ORD-57811,3/19/2025,Science,Books,5,233.92,PayPal,Processing,1169.60
4,104,Customer_104,ORD-93614,10/20/2025,Biography,Books,1,552.51,Cash on Delivery,Processing,552.51

In [4]:
df.describe()

               ID         Total
count  103.000000     89.000000
mean   149.640777   1232.949101
std     28.704326   2605.471455
min    100.000000 -20000.000000
25%    125.500000    582.130000
50%    149.000000   1138.760000
75%    174.500000   2153.400000
max    199.000000   4722.700000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103 entries, 0 to 102
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID              103 non-null    int64
 1    Customer_Name  103 non-null    object
 2   Order_ID        103 non-null    object
 3   Order_Date      103 non-null    object
 4   Product         103 non-null    object
 5    Category       95 non-null     object
 6   Quantity        98 non-null     object
 7   Price           98 non-null     object
 8   Payment_Method  103 non-null    object
 9   Status          103 non-null    object
 10  Total           89 non-null     float64
dtypes: float64(1), int64(1), object(9)
memory usage: 9.0+ KB

In [9]:
df.columns

Index(['ID', 'Customer_Name', 'Order_ID', 'Order_Date', 'Product', 'Category',
       'Quantity', 'Price', 'Payment_Method', 'Status', 'Total'],
      dtype='object')

In [7]:
df.isnull().sum()

ID                 0
 Customer_Name     0
Order_ID           0
Order_Date         0
Product            0
 Category          8
Quantity           5
Price              5
Payment_Method     0
Status             0
Total             14
dtype: int64

In [8]:
df=df.rename(columns={" Customer_Name": "Customer_Name", " Category":"Category"})

In [10]:
df.duplicated().sum()

np.int64(1)

In [11]:
df = df.drop_duplicates()

#### **Value formatting-**

In [18]:
print(df["Category"].unique())
print(df["Payment_Method"].unique())
print(df["Status"].unique())

['Home' 'Electronics' 'Sports' 'Books' 'Clothing' nan]
['Cash on Delivery' 'PayPal' 'Bank Transfer' 'Credit Card']
['Shipped' 'Processing' 'Delivered' 'Cancelled' 'Returned']

In [16]:
print(df["Product"].unique())

['Blender' 'Smartphone' 'Tennis Racket' 'Science' 'Biography' 'Basketball'
 'Comics' 'Shoes' 'Fiction' 'Microwave' 'Yoga Mat' 'Vacuum' 'Lamp'
 'T-Shirt' 'Smartwatch' 'Headphones' 'Football' 'Laptop' 'Jacket' 'Jeans']

In [14]:
df["Category"] = df["Category"].str.strip().str.title()
df["Product"] = df["Product"].str.strip().str.title()

In [17]:
df["Category"] = df["Category"].replace({"Electronic": "Electronics"})

In [20]:
df["Price"] = df["Price"].astype(str).str.replace("$", "", regex=False).str.strip()
df["Price"] = df["Price"].replace({"four hundred": 400})

In [21]:
df["Price"] = pd.to_numeric(df["Price"], errors="coerce")

In [26]:
df['Price'] = df['Price'].abs()

In [27]:
df['Quantity'] = df['Quantity'].astype(str).str.extract(r'(\d+)')[0]
df['Quantity'] = pd.to_numeric(df['Quantity'], errors='coerce')

In [28]:
df['Quantity'] = df['Quantity'].abs()

In [30]:
df["Total"] = df["Quantity"] * df ["Price"]

In [29]:
df.dtypes

ID                  int64
Customer_Name      object
Order_ID           object
Order_Date         object
Product            object
Category           object
Quantity          float64
Price             float64
Payment_Method     object
Status             object
Total             float64
dtype: object

In [33]:
df.isnull().sum()

ID                 0
Customer_Name      0
Order_ID           0
Order_Date         0
Product            0
Category           0
Quantity           5
Price              7
Payment_Method     0
Status             0
Total             11
dtype: int64

In [32]:
df['Category'] = df['Category'].fillna('Unknown')

In [37]:
df

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,100,Customer_100,ORD-41285,2024-11-22,Blender,Home,3.0,38.00,Cash on Delivery,Shipped,114.00
1,101,Customer_101,ORD-35783,2025-07-05,Smartphone,Electronics,2.0,NaN,PayPal,Processing,NaN
2,102,Customer_102,ORD-84355,2024-12-23,Tennis Racket,Sports,1.0,389.05,PayPal,Delivered,389.05
3,103,Customer_103,ORD-57811,2025-03-19,Science,Books,5.0,233.92,PayPal,Processing,1169.60
4,104,Customer_104,ORD-93614,2025-10-20,Biography,Books,1.0,552.51,Cash on Delivery,Processing,552.51
...,...,...,...,...,...,...,...,...,...,...,...
97,197,Customer_197,ORD-79139,2025-06-23,Blender,Home,1.0,160.16,PayPal,Cancelled,160.16
98,198,Customer_198,ORD-14608,2025-07-27,Vacuum,Unknown,2.0,497.01,Cash on Delivery,Shipped,994.02
99,199,Customer_199,ORD-82922,2025-01-22,Blender,Home,5.0,372.28,Credit Card,Shipped,1861.40
100,175,Customer_175,ORD-56651,2025-02-24,Headphones,Electronics,1.0,111.36,Credit Card,Processing,111.36
101,142,Customer_142,ORD-69018,2025-10-30,Shoes,Clothing,5.0,645.26,Credit Card,Shipped,3226.30

In [35]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'], format='mixed', errors='coerce')

In [36]:
df[df['Order_Date'].isnull()]

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
92,192,Customer_192,ORD-35144,NaT,Jacket,Clothing,4.0,203.63,Credit Card,Returned,814.52

In [38]:
df.to_csv("ecom_data_clean.csv", index=False)